config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


   scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about' ,as: 'about'

    get '/customers/my_page' => 'customers#show' ,as: 'my_page'
    get '/customers/information/edit' => 'customers#edit' ,as: 'information_edit'
    get '/customers/unsubscribe' => 'customers#unsubscribe' ,as: 'unsubscribe'
    patch '/customers/information' => 'customers#update' ,as: 'information'
    patch '/customers/withdraw' => 'customers#withdraw' ,as: 'withdraw'

    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'confirm'
        get 'thanks'
      end
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end

end

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_many :orders , dependent: :destroy
  has_many :addresses , dependent: :destroy
  has_many :cart_items , dependent: :destroy
  
  def full_name
    first_name + last_name
  end
  
 
  
  def status
    is_active ? '有効' : '退会'
  end
  
  #validates :password, presence: true, length: { minimum: 6 }

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  has_many :addresses, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
   before_action :set_customer, only: [:edit, :update]
   
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: '会員情報が更新されました。'
    else
      flash[:notice] = "失敗しました"
      render :edit
    end
  end 
  
  

  
  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end 
end 

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container mt-5">
<% if @customer.errors.any? %>
  <div class="alert alert-danger">
    <h4><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h4>
    <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <h1 class="mb-4"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h1>

  <%= form_with(model: @customer, url: admin_customer_path(@customer), method: :patch, local: true) do |f| %>
    <div class="form-group row mb-3">
      <label class="col-sm-2 col-form-label">会員ID</label>
      <div class="col-sm-10">
        <p class="form-control-plaintext"><%= @customer.id %></p>
      </div>
    </div>

    <div class="form-group row mb-3">
      <label class="col-sm-2 col-form-label">氏名</label>
      <div class="col-sm-5">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="col-sm-5">
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <label class="col-sm-2 col-form-label">フリガナ</label>
      <div class="col-sm-5">
        <%= f.text_field :last_name_kana, class: "form-control" %>
      </div>
      <div class="col-sm-5">
        <%= f.text_field :first_name_kana, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <label class="col-sm-2 col-form-label">郵便番号</label>
      <div class="col-sm-10">
        <%= f.text_field :postal_code, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <label class="col-sm-2 col-form-label">住所</label>
      <div class="col-sm-10">
        <%= f.text_field :address, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <label class="col-sm-2 col-form-label">電話番号</label>
      <div class="col-sm-10">
        <%= f.text_field :telephone_number, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <label class="col-sm-2 col-form-label">メールアドレス</label>
      <div class="col-sm-10">
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <label class="col-sm-2 col-form-label">会員ステータス</label>
      <div class="col-sm-10">
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, true, class: "form-check-input", id: "status-active" %>
          <label class="form-check-label" for="status-active">有効</label>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, false, class: "form-check-input", id: "status-inactive" %>
          <label class="form-check-label" for="status-inactive">退会</label>
        </div>
      </div>
    </div>

    <div class="form-group row mb-3">
      <div class="col-sm-10 offset-sm-2">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<% content_for :title, "会員一覧" %>

<div class="container mt-4">
  <h1 class="text-left">会員一覧</h1>
  <table class="table table-striped mt-3">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |c| %>
        <tr>
          <td><%= c.id %></td>
          <td><%= link_to "#{c.last_name} #{c.first_name}", admin_customer_path(c) %></td>
          <td><%= c.email %></td>
          <td>
            <% if c.is_active %>
              <span class="text-success">有効</span>
            <% else %>
              <span class="text-muted">退会済</span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<% content_for :title, "#{@customer.last_name} #{@customer.first_name}の詳細" %>

<div class="container mt-4">
  <h1 class="text-left"><%= @customer.last_name %> <%= @customer.first_name %>の詳細</h1>
  <table class="table table-striped mt-3">
    <tr>
      <th>会員ID</th>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <th>氏名</th>
      <td><%= @customer.last_name %> <%= @customer.first_name %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <th>ステータス</th>
      <td>
        <% if @customer.is_active %>
          <span class="text-success">有効</span>
        <% else %>
          <span class="text-muted">退会済</span>
        <% end %>
      </td>
    </tr>
  </table>
  <div class="row">
    <div class="col-4">
      <%= link_to '会員一覧に戻る', admin_customers_path, class: 'btn btn-secondary mt-3' %>
    </div>
    <div class="col-4">
      <%= link_to '編集', edit_admin_customer_path, class: 'btn btn-success mt-3' %>
    </div>
    <div class="col-4">
        <%= link_to '注文履歴', admin_customers_path, class: 'btn btn-primary mt-3' %>
    </div>
  </div>

  
</div>