config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


   scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about' ,as: 'about'

    get '/customers/my_page' => 'customers#show' ,as: 'my_page'
    get '/customers/information/edit' => 'customers#edit' ,as: 'information_edit'
    get '/customers/unsubscribe' => 'customers#unsubscribe' ,as: 'unsubscribe'
    patch '/customers/information' => 'customers#update' ,as: 'information'
    patch '/customers/withdraw' => 'customers#withdraw' ,as: 'withdraw'

    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'confirm'
        get 'thanks'
      end
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end

end

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/address.rb
class Address < ApplicationRecord
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
  validates :encrypted_password, presence: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  def subtotal
    item.with_tax_price * amount
  end

  belongs_to :customer
  belongs_to :item

  validates :amount, numericality: { less_than_or_equal_to: 10, message: 'は10個以下で指定してください。' }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_many :orders , dependent: :destroy
  has_many :addresses , dependent: :destroy
  has_many :cart_items , dependent: :destroy
  
  def full_name
    first_name + last_name
  end
  
 
  
  def status
    is_active ? '有効' : '退会'
  end
  
  #validates :password, presence: true, length: { minimum: 6 }

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items 
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
 

  def get_image(width, height)
    image.variant(resize_to_limit: [width, height]).processed
  end


  def with_tax_price
    (price * 1.1).floor
  end

  validates :name, presence: { message: "を入力してください" }, length: { maximum: 255, message: "は255文字以内で入力してください" }
  validates :introduction, presence: { message: "を入力してください" }
  validates :price, presence: { message: "を入力してください" }, numericality: { greater_than: 0, message: "は0より大きい数値で入力してください" }
  validates :genre_id, presence: { message: "を選択してください" }
  validates :is_active, inclusion: { in: [true, false], message: "が無効です" }
  validates :image, presence: { message: "をアップロードしてください" }


  #enum is_active: { inactive: 0, active: 1 }

  belongs_to :genre
  has_many :order_details , dependent: :destroy
  has_many :cart_items , dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_payment: 0, payment_confirmation: 1, making: 2, preparation_shipping: 3, shipped: 4 }

  belongs_to :customer
  has_many :order_details , dependent: :destroy

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { making_impossible:0, waiting_production:1, making:2, production_completed:3 }

  def subtotal
    price * amount
  end

  belongs_to :order
  belongs_to :item


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: 'ジャンルが作成されました'
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @order_page = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
   before_action :set_genres, only: [:new, :create]
  def index
    @items = Item.all
    @item_page = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update!(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)

  end

  def set_genres
    @genres = Genre.all
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @customer = @order.customer
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_status: params[:order][:order_status])
    @order_details = @order.order_details
    if params[:order][:order_status] == "payment_confirmation"
      @order_details.update(making_status: "waiting_production")
    end
    
  flash[:notice] = "注文ステータスを変更しました"
  redirect_to admin_order_path(@order)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch, local: true do |f| %>
      <div class="row">
          <h2>ジャンル編集</h2>
      </div>
      <div class="row">
          <div class="col-2"><%= f.label :name, "ジャンル名" %></div>
          <div class="col-4"><%= f.text_field :name %></div>
          <div class="col-4"><%= f.submit "変更を保存する", class: "btn btn-success" %></div>
      </div>
  <% end %>
  <div class="row mt-5">
    <%= link_to "戻る", admin_genres_path, class: "btn btn-secondary" %>
  </div
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <%= form_with model: @genre, url: admin_genres_path, method: :post, local: true do |f| %>
    <div class="row mb-5">
        <h2>ジャンル一覧・追加</h2>
    </div>
    <div class="row">
        <div class="col-2"><%= f.label :name, "ジャンル名" %></div>
        <div class="col-4"><%= f.text_field :name %></div>
        <div class="col-4"><%= f.submit "新規登録", class: "btn btn-success" %></div>
    </div>
  <% end %>
  <div class="row">
      <div class="col-5">
          <table class="table table-bordered">
              <thead>
                  <tr>
                      <th>ジャンル</th>
                      <th></th>
                  </tr>
              </thead>
              <tbody>
                  <% @genres.each do |g| %>
                    <tr>
                        <td class="p-2"><%= g.name %></td>
                        <td class="p-2"><%= link_to "編集する", edit_admin_genre_path(g), class: "btn btn-success" %></td>
                    </tr>
                  <% end %>
              </tbody>
          </table>
      </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container py-4">
  <div class= "row">
    <div class="col-md-12">

　　　<div class="order-show-title">
        <h5 class="fs-6">
          <span class="px-2">注文履歴詳細</span>
        </h5>
      </div>

      <table>
        <tbody>
          <tr>
            <th>購入者</th>
            <td class="underline"><%= @customer.full_name %></td>
          </tr>
          <tr>
            <th>注文日</th>
            <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
          </tr>
          <tr>
            <th>配送先</th>
            <td><%= @order.postal_code + " " + @order.address %></td>
          </tr>
          <tr>
            <th></th>
            <td><%= @order.name %></td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <th>注文ステータス</th>
            <td>
              <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
              <div class="d-flex align-items-center">
                <%= f.select :order_status, Order.order_statuses_i18n.keys.map { |status| [I18n.t("enums.order.order_status.#{status}"), status] }, {}, class: "form-control " %>
                <%= f.submit "更新", class: "btn btn-success" %>
              </div>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <br>
      <br>
      <br>

      <div class="d-flex">

         <div class="col-md-8">
      <table class="table table-borderless">
        <thead class="bg-light">
          <tr>
            <th>商品名</th>
            <th>単価(税込み)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.price %></td>
              <td><%= order_detail.amount %></td>
              <td><%= order_detail.subtotal %></td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true do |f| %>
                  <div class="d-flex align-items-center">
                    <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map { |status| [I18n.t("enums.order_detail.making_status.#{status}"), status] }, {}, class: "form-control" %>
                    <%= f.submit "更新", class: "btn btn-success" %>
                  </div>
                <% end %>
              </td>
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>

      <br>
      <br>
      <br>

      <div class="col-md-4">
      <table>
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= @order.total_payment - @order.shipping_cost %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= @order.shipping_cost %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><%= @order.total_payment %>円</td>
          </tr>
        </tbody>
      </table>
      </div>
      </div>

          </div>
        </div>
      </div>

app/views/publics/items/index.html.erb
<h1>Public::Items#index</h1>
<p>Find me in app/views/public/items/index.html.erb</p>

app/views/publics/items/show.html.erb
<h1>Public::Items#show</h1>
<p>Find me in app/views/public/items/show.html.erb</p>

app/views/publics/orders/index.html.erb
<h1>Public::Orders#index</h1>
<p>Find me in app/views/public/orders/index.html.erb</p>

app/views/publics/orders/new.html.erb
<h1>Public::Orders#new</h1>
<p>Find me in app/views/public/orders/new.html.erb</p>

app/views/publics/orders/show.html.erb
<h1>Public::Orders#show</h1>
<p>Find me in app/views/public/orders/show.html.erb</p>

app/views/publics/orders/thanks.html.erb
<h1>Public::Orders#thanks</h1>
<p>Find me in app/views/public/orders/thanks.html.erb</p>